import { count, IRS_MILEAGE_RATE, is, num, ratio, sum, type GigConfig, type RecordData } from "../schema";

// E-commerce & Retail. Order/inventory economics are the point here:
// every sale shows its real profit after cost of goods, platform fees and
// shipping, and the KPIs answer "am I actually making money?".

const profit = (d: RecordData) =>
  num(d.sale_total) + num(d.shipping_charged) - num(d.item_cost) - num(d.platform_fees) - num(d.shipping_cost);

export const ECOMMERCE_CONFIGS: GigConfig[] = [
  {
    categories: ["Print-on-Demand Shop"],
    tagline: "Designs, products and orders, with Printful syncing orders, costs and tracking automatically.",
    usesClients: false,
    collections: [
      {
        key: "orders",
        label: "Orders",
        singular: "Order",
        titleField: "order_no",
        dateField: "order_date",
        statusField: "status",
        sort: { field: "order_date", dir: "desc" },
        fields: [
          { key: "order_no", label: "Order #", type: "text", required: true },
          { key: "order_date", label: "Order date", type: "date", required: true },
          { key: "customer", label: "Customer", type: "text" },
          { key: "product", label: "Products", type: "text", placeholder: "e.g. Monkey Tee (L) x2" },
          { key: "channel", label: "Sales channel", type: "select", options: ["Shopify", "Etsy", "Printful store", "Website", "TikTok Shop", "Other"] },
          { key: "sale_total", label: "Customer paid (items)", type: "money", list: true },
          { key: "shipping_charged", label: "Shipping charged", type: "money" },
          { key: "item_cost", label: "Printful cost (fulfillment)", type: "money", list: true, help: "What the print provider charged you for the items" },
          { key: "shipping_cost", label: "Printful shipping cost", type: "money" },
          { key: "platform_fees", label: "Marketplace / payment fees", type: "money" },
          { key: "status", label: "Status", type: "select", options: ["Pending", "In production", "On hold", "Shipped", "Delivered", "Returned", "Canceled", "Failed"], default: "Pending" },
          { key: "tracking_url", label: "Tracking link", type: "url" },
          { key: "external_ref", label: "Printful order ID", type: "text", help: "Filled in automatically by the Printful sync" },
        ],
        computed: [
          { key: "profit", label: "Profit", format: "money", fn: profit },
          { key: "margin", label: "Margin", format: "percent", fn: (d) => ratio(profit(d), num(d.sale_total) + num(d.shipping_charged)) },
        ],
        income: (d) => (is("status", "Canceled", "Failed")(d) ? 0 : num(d.sale_total) + num(d.shipping_charged)),
        expense: (d) => (is("status", "Canceled", "Failed")(d) ? 0 : num(d.item_cost) + num(d.shipping_cost) + num(d.platform_fees)),
        csvImport: {
          hint: "Export orders from Shopify (Orders → Export) or Etsy (Settings → Options → Download Data).",
          guess: { order_no: ["name", "order", "order id", "order number", "order #"], order_date: ["created at", "sale date", "order date", "date"], customer: ["billing name", "buyer", "full name", "customer"], sale_total: ["subtotal", "order value", "item total", "items total"], shipping_charged: ["shipping", "shipping charged"], platform_fees: ["fees", "card processing fees", "transaction fees"] },
          idField: "order_no",
        },
      },
      {
        key: "products",
        label: "Products",
        singular: "Product",
        titleField: "name",
        statusField: "status",
        fields: [
          { key: "name", label: "Product", type: "text", required: true, placeholder: "e.g. Sticky Monkey Classic Tee" },
          { key: "design", label: "Design", type: "ref", ref: "designs" },
          { key: "blank", label: "Blank / base product", type: "text", placeholder: "e.g. Bella+Canvas 3001" },
          { key: "base_cost", label: "Base cost (incl. print)", type: "money", list: true },
          { key: "ship_cost", label: "Avg. shipping cost", type: "money" },
          { key: "retail_price", label: "Retail price", type: "money", list: true },
          { key: "fee_pct", label: "Marketplace fee", type: "percent", default: 6.5, help: "Etsy ~6.5% + payment processing ~3%" },
          { key: "status", label: "Status", type: "select", options: ["Idea", "Mockup", "Live", "Retired"], default: "Idea" },
          { key: "listing_url", label: "Listing link", type: "url" },
        ],
        computed: [
          {
            key: "unit_profit",
            label: "Profit / sale",
            format: "money",
            fn: (d) => num(d.retail_price) * (1 - num(d.fee_pct) / 100) - num(d.base_cost) - num(d.ship_cost),
          },
          {
            key: "unit_margin",
            label: "Margin",
            format: "percent",
            fn: (d) => ratio(num(d.retail_price) * (1 - num(d.fee_pct) / 100) - num(d.base_cost) - num(d.ship_cost), num(d.retail_price)),
          },
        ],
      },
      {
        key: "designs",
        label: "Designs",
        singular: "Design",
        titleField: "title",
        statusField: "status",
        fields: [
          { key: "title", label: "Design", type: "text", required: true },
          { key: "niche", label: "Niche / audience", type: "text", placeholder: "e.g. dog moms, retro gamers" },
          { key: "file_url", label: "Artwork file link", type: "url", help: "Drive / Dropbox link to the print-ready file" },
          { key: "license", label: "Rights", type: "select", options: ["My original", "Commissioned (I own rights)", "Licensed", "Public domain"], default: "My original" },
          { key: "status", label: "Status", type: "select", options: ["Idea", "In progress", "Ready", "Published"], default: "Idea" },
          { key: "cost", label: "Design cost", type: "money", help: "Paid to a designer or for assets" },
          { key: "made_on", label: "Date", type: "date" },
        ],
        dateField: "made_on",
        expense: (d) => num(d.cost),
      },
      {
        key: "expenses",
        label: "Expenses",
        singular: "Expense",
        titleField: "item",
        dateField: "date",
        fields: [
          { key: "item", label: "Expense", type: "text", required: true, placeholder: "e.g. Shopify plan, samples, ads" },
          { key: "date", label: "Date", type: "date", required: true },
          { key: "category", label: "Category", type: "select", options: ["Store subscription", "Samples", "Advertising", "Mockups / design tools", "Fonts / assets", "Other"] },
          { key: "amount", label: "Amount", type: "money", required: true },
        ],
        expense: (d) => num(d.amount),
      },
    ],
    kpis: [
      { label: "Revenue YTD", format: "money", value: (c) => c.incomeYtd },
      { label: "Profit YTD", format: "money", value: (c) => c.incomeYtd - c.expenseYtd },
      { label: "Orders this month", format: "number", value: (c) => count(c.month("orders"), (d) => !is("status", "Canceled", "Failed")(d)) },
      { label: "Avg. profit / order", format: "money", value: (c) => ratio(sum(c.ytd("orders"), profit), count(c.ytd("orders"))) },
      { label: "Needs attention", format: "number", value: (c) => count(c.all("orders"), is("status", "On hold", "Failed")), hint: "On hold or failed at Printful" },
    ],
    checklist: {
      label: "Launch checklist",
      items: [
        "Create a free Printful account and connect your store (Shopify, Etsy, or Printful's own)",
        "Order a sample of each product before listing it (check print quality and fit)",
        "Price each product with the Products tab, target 30%+ margin after fees and shipping",
        "Connect Printful below so orders, costs and tracking sync automatically",
        "Check sales tax: marketplaces like Etsy collect it, your own store may need to",
        "Only use artwork you own or are licensed to sell",
      ],
    },
    integrations: [
      { kind: "printful" },
      { kind: "shopify_webhook" },
      { kind: "link", label: "Printful dashboard", url: "https://www.printful.com/dashboard" },
      { kind: "link", label: "Printful API tokens", url: "https://developers.printful.com/tokens", note: "Create a private token here to connect" },
    ],
    resources: [
      { label: "Printful pricing calculator", url: "https://www.printful.com/pricing" },
      { label: "Printify (alternative supplier)", url: "https://printify.com" },
      { label: "Etsy seller fees", url: "https://www.etsy.com/legal/fees/" },
    ],
  },
  {
    categories: ["Dropshipping Store"],
    tagline: "Store orders from Shopify, supplier costs, and true profit per order.",
    usesClients: false,
    collections: [
      {
        key: "orders",
        label: "Orders",
        singular: "Order",
        titleField: "order_no",
        dateField: "order_date",
        statusField: "status",
        sort: { field: "order_date", dir: "desc" },
        fields: [
          { key: "order_no", label: "Order #", type: "text", required: true },
          { key: "order_date", label: "Order date", type: "date", required: true },
          { key: "customer", label: "Customer", type: "text" },
          { key: "product", label: "Products", type: "text" },
          { key: "channel", label: "Sales channel", type: "select", options: ["Shopify", "WooCommerce", "TikTok Shop", "Amazon", "Other"], default: "Shopify" },
          { key: "sale_total", label: "Customer paid (items)", type: "money", list: true },
          { key: "shipping_charged", label: "Shipping charged", type: "money" },
          { key: "item_cost", label: "Supplier cost", type: "money", list: true, help: "What you paid the supplier (AliExpress, CJ, Spocket…)" },
          { key: "shipping_cost", label: "Supplier shipping", type: "money" },
          { key: "platform_fees", label: "Payment / app fees", type: "money" },
          { key: "supplier", label: "Supplier", type: "ref", ref: "suppliers" },
          { key: "status", label: "Status", type: "select", options: ["New", "Ordered from supplier", "Shipped", "Delivered", "Refunded", "Canceled"], default: "New" },
          { key: "tracking_url", label: "Tracking link", type: "url" },
          { key: "external_ref", label: "Store order ID", type: "text" },
        ],
        computed: [
          { key: "profit", label: "Profit", format: "money", fn: profit },
          { key: "margin", label: "Margin", format: "percent", fn: (d) => ratio(profit(d), num(d.sale_total) + num(d.shipping_charged)) },
        ],
        income: (d) => (is("status", "Canceled", "Refunded")(d) ? 0 : num(d.sale_total) + num(d.shipping_charged)),
        expense: (d) => (is("status", "Canceled")(d) ? 0 : num(d.item_cost) + num(d.shipping_cost) + num(d.platform_fees)),
        csvImport: {
          hint: "Shopify: Orders → Export → CSV for Excel. Supplier costs can be filled in after.",
          guess: { order_no: ["name", "order", "order number"], order_date: ["created at", "date"], customer: ["billing name", "shipping name"], sale_total: ["subtotal"], shipping_charged: ["shipping"], product: ["lineitem name"] },
          idField: "order_no",
        },
      },
      {
        key: "products",
        label: "Products",
        singular: "Product",
        titleField: "name",
        statusField: "status",
        fields: [
          { key: "name", label: "Product", type: "text", required: true },
          { key: "supplier", label: "Supplier", type: "ref", ref: "suppliers" },
          { key: "supplier_cost", label: "Supplier cost", type: "money", list: true },
          { key: "ship_cost", label: "Shipping cost", type: "money" },
          { key: "price", label: "Your price", type: "money", list: true },
          { key: "ad_cpa", label: "Ad cost per sale", type: "money", help: "Average ad spend to get one sale" },
          { key: "ship_days", label: "Delivery time", type: "number", unit: "days" },
          { key: "status", label: "Status", type: "select", options: ["Testing", "Winner", "Paused", "Dropped"], default: "Testing" },
          { key: "supplier_url", label: "Supplier link", type: "url" },
        ],
        computed: [
          { key: "unit_profit", label: "Profit / sale", format: "money", fn: (d) => num(d.price) * 0.97 - num(d.supplier_cost) - num(d.ship_cost) - num(d.ad_cpa) },
          { key: "breakeven_roas", label: "Break-even ROAS", format: "number", fn: (d) => ratio(num(d.price), num(d.price) * 0.97 - num(d.supplier_cost) - num(d.ship_cost)) },
        ],
      },
      {
        key: "suppliers",
        label: "Suppliers",
        singular: "Supplier",
        titleField: "name",
        fields: [
          { key: "name", label: "Supplier", type: "text", required: true },
          { key: "platform", label: "Platform", type: "select", options: ["AliExpress", "CJ Dropshipping", "Spocket", "Zendrop", "Alibaba", "Domestic wholesaler", "Other"] },
          { key: "contact", label: "Contact", type: "text" },
          { key: "avg_ship_days", label: "Avg. shipping time", type: "number", unit: "days" },
          { key: "rating", label: "Reliability", type: "rating" },
          { key: "url", label: "Store link", type: "url" },
          { key: "notes", label: "Notes", type: "textarea" },
        ],
      },
      {
        key: "ads",
        label: "Ad spend",
        singular: "Ad spend entry",
        titleField: "campaign",
        dateField: "date",
        fields: [
          { key: "campaign", label: "Campaign", type: "text", required: true },
          { key: "platform", label: "Platform", type: "select", options: ["Meta", "TikTok", "Google", "Pinterest", "Influencer", "Other"] },
          { key: "date", label: "Date", type: "date", required: true },
          { key: "spend", label: "Spend", type: "money", required: true },
          { key: "sales", label: "Sales attributed", type: "money" },
        ],
        computed: [{ key: "roas", label: "ROAS", format: "number", fn: (d) => ratio(num(d.sales), num(d.spend)) }],
        expense: (d) => num(d.spend),
      },
      {
        key: "expenses",
        label: "Expenses",
        singular: "Expense",
        titleField: "item",
        dateField: "date",
        fields: [
          { key: "item", label: "Expense", type: "text", required: true, placeholder: "e.g. Shopify plan, apps, samples" },
          { key: "date", label: "Date", type: "date", required: true },
          { key: "amount", label: "Amount", type: "money", required: true },
        ],
        expense: (d) => num(d.amount),
      },
    ],
    kpis: [
      { label: "Revenue YTD", format: "money", value: (c) => c.incomeYtd },
      { label: "Profit YTD", format: "money", value: (c) => c.incomeYtd - c.expenseYtd, hint: "After supplier, ads and fees" },
      { label: "Ad ROAS YTD", format: "number", value: (c) => ratio(sum(c.ytd("ads"), "sales"), sum(c.ytd("ads"), "spend")) },
      { label: "Orders to send to supplier", format: "number", value: (c) => count(c.all("orders"), is("status", "New")) },
      { label: "Missing supplier cost", format: "number", value: (c) => count(c.all("orders"), (d) => !num(d.item_cost) && !is("status", "Canceled", "Refunded")(d)) },
    ],
    checklist: {
      label: "Launch checklist",
      items: [
        "Order samples from your supplier and check quality and shipping time yourself",
        "Set clear shipping times and a return policy on your store",
        "Price products so Profit / sale is still positive after ad cost",
        "Add the Shopify order webhook below so orders land here automatically",
        "Register for sales tax where required (your state may require a seller's permit)",
        "Track ad spend weekly and stop products under break-even ROAS",
      ],
    },
    integrations: [
      { kind: "shopify_webhook" },
      { kind: "link", label: "Shopify admin", url: "https://admin.shopify.com" },
      { kind: "link", label: "CJ Dropshipping", url: "https://cjdropshipping.com" },
    ],
    resources: [
      { label: "FTC: shipping rule (30-day rule)", url: "https://www.ftc.gov/business-guidance/resources/business-guide-ftcs-mail-internet-or-telephone-order-merchandise-rule" },
      { label: "Spocket (US/EU suppliers)", url: "https://www.spocket.co" },
    ],
  },
  {
    categories: ["Amazon / eBay Reseller"],
    tagline: "Inventory from sourcing to sale, with real profit after fees and shipping.",
    usesClients: false,
    collections: [
      {
        key: "inventory",
        label: "Inventory",
        singular: "Item",
        titleField: "item",
        dateField: "sold_date",
        statusField: "status",
        sort: { field: "bought_date", dir: "desc" },
        fields: [
          { key: "item", label: "Item", type: "text", required: true },
          { key: "sku", label: "SKU", type: "text" },
          { key: "source", label: "Sourced from", type: "select", options: ["Thrift store", "Garage / estate sale", "Retail arbitrage", "Online arbitrage", "Wholesale", "Private label", "Liquidation", "Other"] },
          { key: "bought_date", label: "Bought", type: "date" },
          { key: "cost", label: "Cost", type: "money", list: true },
          { key: "qty", label: "Qty", type: "number", default: 1 },
          { key: "platform", label: "Selling on", type: "select", options: ["eBay", "Amazon FBA", "Amazon FBM", "Poshmark", "Mercari", "Facebook Marketplace", "Whatnot", "Other"] },
          { key: "list_price", label: "List price", type: "money" },
          { key: "status", label: "Status", type: "select", options: ["To list", "Listed", "Sold", "Shipped", "Returned", "Donated / written off"], default: "To list" },
          { key: "sold_date", label: "Sold", type: "date" },
          { key: "sold_price", label: "Sold for", type: "money", list: true },
          { key: "shipping_charged", label: "Shipping charged", type: "money" },
          { key: "fees", label: "Platform fees", type: "money", help: "eBay final value fee or Amazon referral + FBA fees" },
          { key: "shipping_cost", label: "Shipping label", type: "money" },
        ],
        computed: [
          {
            key: "profit",
            label: "Profit",
            format: "money",
            fn: (d) =>
              is("status", "Sold", "Shipped")(d)
                ? num(d.sold_price) + num(d.shipping_charged) - num(d.cost) - num(d.fees) - num(d.shipping_cost)
                : null,
          },
          {
            key: "roi",
            label: "ROI",
            format: "percent",
            fn: (d) =>
              is("status", "Sold", "Shipped")(d)
                ? ratio(num(d.sold_price) + num(d.shipping_charged) - num(d.cost) - num(d.fees) - num(d.shipping_cost), num(d.cost))
                : null,
          },
        ],
        // Cost of goods is deducted when the item sells (inventory isn't an expense until then).
        income: (d) => (is("status", "Sold", "Shipped")(d) ? num(d.sold_price) + num(d.shipping_charged) : 0),
        expense: (d) => (is("status", "Sold", "Shipped")(d) ? num(d.cost) + num(d.fees) + num(d.shipping_cost) : is("status", "Donated / written off")(d) ? num(d.cost) : 0),
        csvImport: {
          hint: "eBay: Seller Hub → Orders → Download report. Amazon: Reports → Payments → Transaction View.",
          guess: { item: ["item title", "title", "description", "product details"], sku: ["custom label (sku)", "sku"], sold_date: ["sale date", "date/time", "date"], sold_price: ["sold for", "item subtotal", "product sales", "total price"], shipping_charged: ["shipping and handling", "shipping credits"], fees: ["final value fee - fixed", "selling fees", "fba fees"], },
          idField: "sku",
        },
      },
      {
        key: "sourcing",
        label: "Sourcing trips",
        singular: "Sourcing trip",
        titleField: "place",
        dateField: "date",
        fields: [
          { key: "place", label: "Where", type: "text", required: true },
          { key: "date", label: "Date", type: "date", required: true },
          { key: "items", label: "Items bought", type: "number" },
          { key: "spent", label: "Spent (record items in Inventory)", type: "money", help: "For reference; item costs count when each item sells" },
          { key: "miles", label: "Miles driven", type: "number", unit: "mi" },
        ],
        computed: [{ key: "mileage", label: "Mileage deduction", format: "money", fn: (d) => num(d.miles) * IRS_MILEAGE_RATE }],
        expense: (d) => num(d.miles) * IRS_MILEAGE_RATE,
      },
      {
        key: "expenses",
        label: "Expenses",
        singular: "Expense",
        titleField: "item",
        dateField: "date",
        fields: [
          { key: "item", label: "Expense", type: "text", required: true, placeholder: "e.g. poly mailers, store subscription" },
          { key: "date", label: "Date", type: "date", required: true },
          { key: "category", label: "Category", type: "select", options: ["Shipping supplies", "Subscription / store fee", "Storage", "Equipment", "Other"] },
          { key: "amount", label: "Amount", type: "money", required: true },
        ],
        expense: (d) => num(d.amount),
      },
    ],
    kpis: [
      { label: "Sales YTD", format: "money", value: (c) => c.incomeYtd },
      { label: "Profit YTD", format: "money", value: (c) => c.incomeYtd - c.expenseYtd },
      { label: "Inventory on hand (cost)", format: "money", value: (c) => sum(c.all("inventory").filter(is("status", "To list", "Listed")), (d) => num(d.cost)) },
      { label: "Items to list", format: "number", value: (c) => count(c.all("inventory"), is("status", "To list")) },
      { label: "Sell-through", format: "percent", value: (c) => ratio(count(c.all("inventory"), is("status", "Sold", "Shipped")), count(c.all("inventory"))) },
    ],
    checklist: {
      label: "Getting started",
      items: [
        "Check your state's resale certificate so you don't pay sales tax on inventory",
        "Log every item's cost when you buy it, it's deducted when the item sells",
        "Track sourcing miles, they're deductible",
        "Check Amazon category / brand restrictions before buying to resell",
        "Expect a 1099-K from eBay/Amazon; your profit here is what's taxed, not the gross",
      ],
    },
    integrations: [
      { kind: "link", label: "eBay Seller Hub", url: "https://www.ebay.com/sh/ovw" },
      { kind: "link", label: "Amazon Seller Central", url: "https://sellercentral.amazon.com" },
    ],
    resources: [
      { label: "eBay fee calculator", url: "https://www.ebay.com/sellercenter/selling/seller-fees" },
      { label: "Amazon FBA revenue calculator", url: "https://sellercentral.amazon.com/revcal" },
    ],
  },
  {
    categories: ["Etsy Shop Owner"],
    tagline: "Listings with true cost of materials and time, orders, and Etsy fees.",
    usesClients: false,
    collections: [
      {
        key: "orders",
        label: "Orders",
        singular: "Order",
        titleField: "order_no",
        dateField: "order_date",
        statusField: "status",
        sort: { field: "order_date", dir: "desc" },
        fields: [
          { key: "order_no", label: "Order #", type: "text", required: true },
          { key: "order_date", label: "Order date", type: "date", required: true },
          { key: "buyer", label: "Buyer", type: "text" },
          { key: "listing", label: "Listing", type: "ref", ref: "listings" },
          { key: "qty", label: "Qty", type: "number", default: 1 },
          { key: "sale_total", label: "Item total", type: "money", list: true },
          { key: "shipping_charged", label: "Shipping charged", type: "money" },
          { key: "etsy_fees", label: "Etsy fees", type: "money", help: "Transaction 6.5% + payment ~3% + $0.25 + listing $0.20" },
          { key: "materials", label: "Materials cost", type: "money" },
          { key: "shipping_cost", label: "Shipping label", type: "money" },
          { key: "status", label: "Status", type: "select", options: ["New", "Making", "Ready to ship", "Shipped", "Delivered", "Refunded", "Canceled"], default: "New" },
          { key: "ship_by", label: "Ship by", type: "date" },
        ],
        computed: [
          {
            key: "profit",
            label: "Profit",
            format: "money",
            fn: (d) => num(d.sale_total) + num(d.shipping_charged) - num(d.etsy_fees) - num(d.materials) - num(d.shipping_cost),
          },
        ],
        income: (d) => (is("status", "Refunded", "Canceled")(d) ? 0 : num(d.sale_total) + num(d.shipping_charged)),
        expense: (d) => (is("status", "Canceled")(d) ? 0 : num(d.etsy_fees) + num(d.materials) + num(d.shipping_cost)),
        csvImport: {
          hint: "Etsy: Shop Manager → Settings → Options → Download Data → Orders (CSV).",
          guess: { order_no: ["order id", "sale id"], order_date: ["sale date", "order date"], buyer: ["full name", "buyer", "ship name"], sale_total: ["order value", "item total"], shipping_charged: ["shipping"], etsy_fees: ["card processing fees", "fees"], qty: ["number of items", "quantity"] },
          idField: "order_no",
        },
      },
      {
        key: "listings",
        label: "Listings",
        singular: "Listing",
        titleField: "title",
        statusField: "status",
        fields: [
          { key: "title", label: "Listing", type: "text", required: true },
          { key: "materials_cost", label: "Materials / unit", type: "money", list: true },
          { key: "minutes", label: "Time to make", type: "number", unit: "min" },
          { key: "hourly", label: "Your hourly rate", type: "money", default: 20 },
          { key: "price", label: "Price", type: "money", list: true },
          { key: "stock", label: "In stock", type: "number" },
          { key: "status", label: "Status", type: "select", options: ["Draft", "Active", "Sold out", "Inactive"], default: "Draft" },
          { key: "url", label: "Etsy link", type: "url" },
        ],
        computed: [
          {
            key: "true_cost",
            label: "True cost",
            format: "money",
            fn: (d) => num(d.materials_cost) + (num(d.minutes) / 60) * num(d.hourly) + num(d.price) * 0.095 + 0.45,
          },
          {
            key: "profit_after_time",
            label: "Profit after your time",
            format: "money",
            fn: (d) => num(d.price) - (num(d.materials_cost) + (num(d.minutes) / 60) * num(d.hourly) + num(d.price) * 0.095 + 0.45),
          },
        ],
      },
      {
        key: "materials",
        label: "Supplies",
        singular: "Supply purchase",
        titleField: "item",
        dateField: "date",
        fields: [
          { key: "item", label: "Supply", type: "text", required: true },
          { key: "vendor", label: "Vendor", type: "text" },
          { key: "date", label: "Date", type: "date", required: true },
          { key: "amount", label: "Amount", type: "money", required: true },
          { key: "note", label: "Note", type: "text", help: "Leave Materials blank on orders if you deduct supplies here instead" },
        ],
        expense: (d) => num(d.amount),
      },
    ],
    kpis: [
      { label: "Sales YTD", format: "money", value: (c) => c.incomeYtd },
      { label: "Profit YTD", format: "money", value: (c) => c.incomeYtd - c.expenseYtd },
      { label: "To make / ship", format: "number", value: (c) => count(c.all("orders"), is("status", "New", "Making", "Ready to ship")) },
      { label: "Orders this month", format: "number", value: (c) => count(c.month("orders")) },
      { label: "Avg. order", format: "money", value: (c) => ratio(sum(c.ytd("orders"), "sale_total"), count(c.ytd("orders"))) },
    ],
    checklist: {
      label: "Shop checklist",
      items: [
        "Price every listing with the Listings tab so your time is paid, not just materials",
        "Count Etsy fees: $0.20 listing, 6.5% transaction, ~3% + $0.25 payment processing",
        "Etsy collects sales tax in most states; check whether you need a seller's permit",
        "Import your orders CSV monthly",
        "Keep supply receipts, they're deductible",
      ],
    },
    integrations: [{ kind: "link", label: "Etsy Shop Manager", url: "https://www.etsy.com/your/shops/me/dashboard" }],
    resources: [
      { label: "Etsy fees & payments policy", url: "https://www.etsy.com/legal/fees/" },
      { label: "Etsy Seller Handbook", url: "https://www.etsy.com/seller-handbook" },
    ],
  },
  {
    categories: ["Flea Market / Pop-Up Vendor"],
    tagline: "Events and booth fees, inventory, and what each market actually made you.",
    usesClients: false,
    collections: [
      {
        key: "events",
        label: "Markets",
        singular: "Market day",
        titleField: "name",
        dateField: "date",
        statusField: "status",
        sort: { field: "date", dir: "desc" },
        fields: [
          { key: "name", label: "Market / event", type: "text", required: true },
          { key: "date", label: "Date", type: "date", required: true },
          { key: "location", label: "Location", type: "text" },
          { key: "status", label: "Status", type: "select", options: ["Applied", "Accepted", "Paid", "Done", "Canceled"], default: "Applied" },
          { key: "booth_fee", label: "Booth fee", type: "money" },
          { key: "cash_sales", label: "Cash sales", type: "money" },
          { key: "card_sales", label: "Card sales", type: "money" },
          { key: "card_fees", label: "Card reader fees", type: "money", help: "Square/SumUp ~2.6% + 15¢" },
          { key: "cogs", label: "Cost of items sold", type: "money" },
          { key: "hours", label: "Hours (incl. setup)", type: "number", unit: "h" },
          { key: "miles", label: "Miles driven", type: "number", unit: "mi" },
          { key: "foot_traffic", label: "Foot traffic", type: "select", options: ["Slow", "OK", "Busy"] },
        ],
        computed: [
          { key: "sales", label: "Sales", format: "money", fn: (d) => num(d.cash_sales) + num(d.card_sales) },
          {
            key: "profit",
            label: "Profit",
            format: "money",
            fn: (d) => num(d.cash_sales) + num(d.card_sales) - num(d.booth_fee) - num(d.card_fees) - num(d.cogs) - num(d.miles) * IRS_MILEAGE_RATE,
          },
          {
            key: "per_hour",
            label: "$ / hour",
            format: "money",
            fn: (d) => ratio(num(d.cash_sales) + num(d.card_sales) - num(d.booth_fee) - num(d.card_fees) - num(d.cogs), num(d.hours)),
          },
        ],
        income: (d) => num(d.cash_sales) + num(d.card_sales),
        expense: (d) => num(d.booth_fee) + num(d.card_fees) + num(d.cogs) + num(d.miles) * IRS_MILEAGE_RATE,
      },
      {
        key: "inventory",
        label: "Inventory",
        singular: "Item",
        titleField: "item",
        fields: [
          { key: "item", label: "Item", type: "text", required: true },
          { key: "category", label: "Category", type: "text" },
          { key: "unit_cost", label: "Cost / unit", type: "money", list: true },
          { key: "price", label: "Price", type: "money", list: true },
          { key: "on_hand", label: "On hand", type: "number" },
        ],
        computed: [
          { key: "margin", label: "Margin", format: "percent", fn: (d) => ratio(num(d.price) - num(d.unit_cost), num(d.price)) },
          { key: "stock_value", label: "Stock value (cost)", format: "money", fn: (d) => num(d.unit_cost) * num(d.on_hand) },
        ],
      },
      {
        key: "expenses",
        label: "Expenses",
        singular: "Expense",
        titleField: "item",
        dateField: "date",
        fields: [
          { key: "item", label: "Expense", type: "text", required: true, placeholder: "e.g. canopy, tables, signage, permit" },
          { key: "date", label: "Date", type: "date", required: true },
          { key: "amount", label: "Amount", type: "money", required: true },
        ],
        expense: (d) => num(d.amount),
      },
    ],
    kpis: [
      { label: "Sales YTD", format: "money", value: (c) => c.incomeYtd },
      { label: "Profit YTD", format: "money", value: (c) => c.incomeYtd - c.expenseYtd },
      { label: "Markets done YTD", format: "number", value: (c) => count(c.ytd("events"), is("status", "Done")) },
      { label: "Best market $/hr", format: "money", value: (c) => Math.max(0, ...c.ytd("events").map((d) => (num(d.hours) ? (num(d.cash_sales) + num(d.card_sales) - num(d.booth_fee) - num(d.card_fees) - num(d.cogs)) / num(d.hours) : 0))) },
      { label: "Upcoming", format: "number", value: (c) => count(c.all("events"), is("status", "Applied", "Accepted", "Paid")) },
    ],
    checklist: {
      label: "Vendor checklist",
      items: [
        "Get your state seller's permit and collect sales tax (most markets require it)",
        "Ask each market if you need a temporary event permit or vendor insurance",
        "Set up a card reader (Square, SumUp) and track its fees",
        "Bring change, price tags, a canopy with weights, and a table cover",
        "Log every market so you know which ones are worth the booth fee",
      ],
    },
    resources: [
      { label: "Square for markets", url: "https://squareup.com/us/en/point-of-sale/retail" },
      { label: "Find your state sales tax permit", url: "https://www.streamlinedsalestax.org/" },
    ],
  },
];
